excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Pods
    - Codegen
    - PhysicianApp/Core/Network/GraphQL

disabled_rules: # rule identifiers to exclude from running
    - block_based_kvo # Swift implementatoin has bugs which lead to a crash - https://bugs.swift.org/browse/SR-5116, https://bugs.swift.org/browse/SR-5117
    - trailing_comma  # There should be a com after the last item in the list
    - todo
    - strict_fileprivate
    - nesting
    - closure_end_indentation
    - unused_setter_value
    - prefixed_toplevel_constant
    - vertical_whitespace_between_cases
    - implicit_return
    - multiple_closures_with_trailing_closure
    - multiline_arguments_brackets
    - empty_xctest_method

opt_in_rules: # some rules are only opt-in
    - attributes
    - anyobject_protocol
#    - closure_body_length
    - closure_spacing
    - collection_alignment
    - conditional_returns_on_newline
    - discouraged_optional_boolean
    - empty_count
    - empty_string
    - empty_xctest_method
    - explicit_init
#    - extension_access_modifier
    - fallthrough
    - fatal_error_message
    - first_where
    - force_unwrapping
    - identical_operands
    - implicit_return
    - joined_default_parameter
    - last_where
    - legacy_random
    - let_var_whitespace
    - literal_expression_end_indentation
    - lower_acl_than_parent
    - modifier_order
    - multiline_arguments
    - multiline_arguments_brackets
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - nimble_operator
    - number_separator
    - operator_usage_whitespace
    - override_in_extension
    - overridden_super_call
    - pattern_matching_keywords
    - private_action
    - private_outlet
    - prohibited_super_call
    - quick_discouraged_call
    - redundant_nil_coalescing
    - redundant_type_annotation
    - required_enum_case
    - single_test_class
    - sorted_first_last
    - sorted_imports
    - toggle_bool
    - unavailable_function
    - unneeded_parentheses_in_closure_argument
    - unowned_variable_capture
    - untyped_error_in_catch
    - unused_import
    - unused_declaration
    - unused_setter_value
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - xct_specific_matcher
    - yoda_condition
    
# to be discussed and enabled
#    - contains_over_first_not_nil
#    - convenience_type
#    - discouraged_object_literal
#    - discouraged_optional_collection
#    - function_default_parameter_at_end
#    - static_operator
#    - switch_case_on_newline
#    - vertical_parameter_alignment_on_call
#    - explicit_type_interface
#    - file_header
#    - file_name
#    - implicitly_unwrapped_optional
#    - missing_docs
#    - nslocalizedstring_key
#    - prohibited_interface_builder
#    - quick_discouraged_focused_test
#    - quick_discouraged_pending_test
#    - todo
#    - trailing_closure

line_length: 200
identifier_name:
    severity: warning
    min_length: 3
    max_length: 40
    excluded:
        - id
        - rx
        - on
    validates_start_with_lowercase: true
type_name:
    min_length: 3
    max_length: 50
    excluded:
        - Id
function_body_length: 50
cyclomatic_complexity:
    warning: 8
    error: 10
force_unwrapping:
    severity: error
redundant_type_annotation:
    severity: error
custom_rules:
  empty_lines_after_type_declarations:
    included: ".*.swift"
    name: "Empty lines after type declarations"
    regex: '(struct|class|enum|protocol|extension) ([\w]+(:\s*[\w\s,]+)* )\{\n\n'
    message: "There should be no empty lines after type declarations"
    severity: error
warning_threshold: 1
conditional_returns_on_newline:
    if_only: true
